#!/bin/sh

#------------------------------------------------------------------
# Copyright (c) 2014 by Belkin, Inc. All Rights Reserved.
#
# This work is subject to U.S. and international copyright laws and
# treaties. No part of this work may be used, practiced, performed,
# copied, distributed, revised, modified, translated, abridged, condensed,
# expanded, collected, compiled, linked, recast, transformed or adapted
# without the prior written consent of Cisco Systems, Inc. Any use or
# exploitation of this work without authorization could subject the
# perpetrator to criminal and civil liability.
#------------------------------------------------------------------


#------------------------------------------------------------------
# This script is run by the init process during the once target
# It signals sysevent to start the network
#------------------------------------------------------------------

sysevent set system-start

