---
- name: Apply Configuration
  uri:
    url: http://{{ xi_ip }}/nagiosxi/api/v1/system/applyconfig?apikey={{ xi_api_key }}
    method: POST
    validate_certs: no
    timeout: 120
  delegate_to: 127.0.0.1
  run_once: true
