#!/bin/bash -e

##########################################
# COPY OVER NEW PNP TEMPLATES
##########################################

echo "Installing new PNP templates..."

# Copy over PNP templates
cp -r ./subcomponents/pnp/mods/templates/* /usr/local/nagios/share/pnp/templates

# Copy over fixes for PNP templates.dist
cp -r ./subcomponents/pnp/mods/templates.dist/* /usr/local/nagios/share/pnp/templates.dist

