#!/bin/sh
source /etc/init.d/ulog_functions.sh
SERVICE_NAME="mdnsd"
SELF_NAME="`basename $0`"
MDNSD=mdnsd
MDNS_CONF_FILE="/tmp/mdnsd.hostname.conf"
HTTP_MDNS_PID_FILE="/var/run/http_tcp_.pid"
service_start() {
   killall $MDNSD > /dev/null 2>&1
   if [ "1" = "$SYSCFG_mdnsd_enabled" ] ; then
       ulog ${SERVICE_NAME} status "starting ${SERVICE_NAME} service" 
       if [ -z "$SYSCFG_bridge_mode" -o "0" = "$SYSCFG_bridge_mode" ] ; then
          if [ -n "$SYSCFG_dot_local_domain" -a -n "$SYSCFG_dot_local_hostname" -a "local" = "$SYSCFG_dot_local_domain" ] ; then
             echo "$SYSCFG_dot_local_hostname" > $MDNS_CONF_FILE
          fi
       else
          if [ -n "$SYSCFG_hostname" ] ; then
             echo "$SYSCFG_hostname" > $MDNS_CONF_FILE
          fi
       fi
       $MDNSD  > /dev/null 2>&1 &
       if [ -x "/sbin/dns-sd" ] ; then
          if [ -z "$SYSCFG_bridge_mode" -o "0" = "$SYSCFG_bridge_mode" ] ; then
             if [ -n "$SYSCFG_dot_local_domain" -a -n "$SYSCFG_dot_local_hostname" ] ; then
                HTTP_HOST=${SYSCFG_dot_local_domain}
             else 
                HTTP_HOST=${SYSCFG_hostname}
             fi
          else
             if [ -z "$SYSCFG_dot_local_domain" ] ; then
                HTTP_HOST=${SYSCFG_dot_local_domain}
             else   
                HTTP_HOST="local"
             fi
             if [ -n "$SYSCFG_hostname" ] ; then
                SYSCFG_dot_local_hostname=$SYSCFG_hostname
             else
                HTTP_HOST=
             fi
          fi
          if [ -n "$HTTP_HOST" ] ; then
             killall -TERM dns-sd > /dev/null 2>&1
             sleep 3
             /sbin/dns-sd -R ${SYSCFG_dot_local_hostname}  _http._tcp ${HTTP_HOST} ${SYSCFG_http_admin_port} &
          fi
       fi
   fi
   sysevent set ${SERVICE_NAME}-errinfo
   sysevent set ${SERVICE_NAME}-status "started"
}
service_stop () {
   ulog ${SERVICE_NAME} status "stopping ${SERVICE_NAME} service" 
    killall $MDNSD > /dev/null 2>&1
   killall -TERM dns-sd > /dev/null 2>&1
   rm -f $MDNS_CONF_FILE
   sysevent set ${SERVICE_NAME}-errinfo
   sysevent set ${SERVICE_NAME}-status "stopped"
}
service_init() {
    FOO=`utctx_cmd get mdnsd_enabled hostname dot_local_domain dot_local_hostname lan_ipaddr http_admin_port bridge_mode` 
    eval $FOO
    if [ -z "$SYSCFG_http_admin_port" ] ; then
      SYSCFG_http_admin_port=80
    fi
}
service_nmbd_stubby() {
  if [ -f "/sbin/nmbd" ] ; then
    if [ ! -f "/sbin/smbd" ] ; then
      killall nmbd
      mkdir -p /tmp/samba
      echo "# This file was autogenerated and will be overwritten" > /tmp/samba/smb.conf
      echo "[global]" >> /tmp/samba/smb.conf
      echo "socket options = TCP_SMB_FAST TCP_NODELAY IPTOS_LOWDELAY SO_RCVBUF=65536 SO_SNDBUF=65536" >> /tmp/samba/smb.conf
      echo "wins server =" >> /tmp/samba/smb.conf
      echo "wins support = no" >> /tmp/samba/smb.conf
      echo "preferred master = auto" >> /tmp/samba/smb.conf
      echo "domain master = auto" >> /tmp/samba/smb.conf
      echo "local master = yes" >> /tmp/samba/smb.conf
      echo "domain logons = no" >> /tmp/samba/smb.conf
      echo "os level = 65" >> /tmp/samba/smb.conf
      echo "netbios name = `hostname`" >> /tmp/samba/smb.conf
      echo "workgroup = WORKGROUP" >> /tmp/samba/smb.conf
      echo "# created : `date`" >> /tmp/samba/smb.conf
      /sbin/nmbd -D
    fi
  fi
}
service_init
case "$1" in
  ${SERVICE_NAME}-start)
      service_start
      ;;
  ${SERVICE_NAME}-stop)
      service_stop
      ;;
  ${SERVICE_NAME}-restart)
      service_stop
      service_start
      ;;
    lan-started)
        service_start
        ;;
    lan-stopped) 
        service_stop
        ;;
  dns-restart)
      service_stop
      sleep 1   
      service_start
      service_nmbd_stubby
      ;;
  *)
      echo "Usage: $SELF_NAME [${SERVICE_NAME}-start|${SERVICE_NAME}-stop|${SERVICE_NAME}-restart|lan-status]" >&2
      exit 3
      ;;
esac
