<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.8.0 setup script
 * Date: Sat, 19 Nov 2022 17:21:33 +0000
 */

$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>